### ISSUE TITLE
Import/Export buttons missing

### ISSUE THREAD

**Issue by thomasoliw** [RabbitMQSimulator/RabbitMQSimulator#14]
Hi, 

I am trying to learn RabbitMQ and have played around with the simulator.
From the README.md file in the installation dir, I understand that there should be a way to Import/Export from RabbitMQ. (My end goal is to Import setup from a production environment and play with it in the simulator).

I use the simulator in a VM (Centos6.5) with the node.js method. I have installed a local rabbitmq-server on the VM and the management plugin, but I don't get the Import/Export buttons in my browser.
Am I reading the instructions wrong? The VM is for learning and the rabbitmq-server is not doing anything but shouldn't I see the Import/Export buttons?

I'm very new to this, so excuse me if this is a silly question.

Best Regards,

Thomas

**Comment by videlalvaro** [comment]
I updated the README showing how to have these buttons enabled

**Comment by Narno** [comment]
Nice, thank you!
